#!/usr/bin/env node
import{spawn}from'node:child_process';import{createHash}from'node:crypto';import{readFile,rename,unlink,writeFile}from'node:fs/promises';import{normalizeWikibaseRdf}from'../../../packages/rdf-sync/src/canonical-rdf-normalizer.js';import{partitionWikibaseSnapshot}from'../../../packages/rdf-sync/src/dataset-partition.js';import{snapshotArtifactNames,validateStandaloneSnapshotManifest}from'../../../services/rdf-sync/src/standalone-snapshot-manifest.js';
if(process.argv.length!==2)throw new Error('SNAPSHOT_PRODUCER_ARGUMENTS_FORBIDDEN');
const snapshotId=process.env.JWB_SNAPSHOT_ID,cursor={timestamp:process.env.JWB_SNAPSHOT_CURSOR_TIMESTAMP,rcid:Number(process.env.JWB_SNAPSHOT_CURSOR_RCID)},names=snapshotArtifactNames(snapshotId),root='/artifacts',raw=`${root}/.${snapshotId}.raw.nt`,pending=`${root}/.${names.rdf}.pending`,marker=`${root}/.${snapshotId}.dump-complete`,artifact=`${root}/${names.rdf}`,manifestPath=`${root}/${names.manifest}`;
if(Number.isNaN(Date.parse(cursor.timestamp))||!Number.isInteger(cursor.rcid)||cursor.rcid<0)throw new Error('INVALID_SNAPSHOT_CURSOR');
await fixedDump(raw);
if(process.env.JWB_SNAPSHOT_RACE_TEST==='true'){await writeFile(marker,'dump-complete\n',{mode:0o644,flag:'wx'});await new Promise(resolve=>setTimeout(resolve,15000));}
try{const source=await readFile(raw,'utf8'),normalized=normalizeWikibaseRdf(source,{sourceKind:'FULL_DUMP'}),dataset=partitionWikibaseSnapshot(normalized.rdf),body=normalized.rdf,manifest=validateStandaloneSnapshotManifest({manifestVersion:'jwb-snapshot-v1',snapshotId,sourceIdentity:process.env.JWB_SOURCE_IDENTITY??'jwb-standalone',createdAt:new Date().toISOString(),cursor,normalizationModel:normalized.normalizationModel,partitionModel:dataset.partitionModel,artifact:{format:'application/n-triples',sha256:createHash('sha256').update(body).digest('hex'),bytes:Buffer.byteLength(body),graphCount:dataset.graphs.size}});await writeFile(pending,body,{mode:0o644,flag:'wx'});await rename(pending,artifact);await writeFile(manifestPath,`${JSON.stringify(manifest)}\n`,{mode:0o644,flag:'wx'});process.stdout.write(`${JSON.stringify(manifest)}\n`);}finally{await unlink(raw).catch(()=>{});await unlink(pending).catch(()=>{});await unlink(marker).catch(()=>{});}
async function fixedDump(destination){const output=await import('node:fs').then(fs=>fs.createWriteStream(destination,{flags:'wx',mode:0o600})),child=spawn('php',['extensions/Wikibase/repo/maintenance/dumpRdf.php','--format','nt','--flavor','full-dump'],{cwd:'/var/www/html',stdio:['ignore','pipe','inherit'],env:process.env}),finished=new Promise((resolve,reject)=>{output.once('finish',()=>resolve());output.once('error',reject)});child.stdout.pipe(output);await new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',code=>code===0?resolve():reject(new Error(`FIXED_DUMP_FAILED_${code}`)));});await finished;}
