#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { validateSemanticFixtureManifest } from '../../../packages/rdf-sync/src/semantic-fixture-manifest.js';

const manifestPath='/artifacts/semantic-fixture.json',base=trustedUrl(process.env.JWB_FIXTURE_SOURCE_URL),adminUser=process.env.JWB_ADMIN_USER,adminPassword=process.env.JWB_ADMIN_PASSWORD;
if(!adminUser||!adminPassword)throw new Error('JWB_FIXTURE_CREDENTIALS_REQUIRED');
try{const existing=validateSemanticFixtureManifest(JSON.parse(await readFile(manifestPath,'utf8')));process.stdout.write(`${JSON.stringify(existing)}\n`);process.exit(0);}catch(error){if(error?.code!=='ENOENT')throw error;}
const session=await login(),properties={};
for(const[key,datatype,ja,en]of[['string','string','意味文字列','semantic string'],['externalId','external-id','意味外部ID','semantic external ID'],['item','wikibase-item','意味項目','semantic item'],['quantity','quantity','意味数量','semantic quantity'],['time','time','意味日時','semantic time'],['qualifier','string','意味修飾子','semantic qualifier'],['reference','url','意味出典','semantic reference']])properties[key]=await create('property',{datatype,labels:terms(ja,en)});
const targetItem=await create('item',{labels:terms('参照先項目','Target item')}),expected={string:'JWB semantic string',externalId:'JWB-EXT-001',quantity:'+42',time:'+2026-08-20T00:00:00Z',qualifier:'qualified',reference:'https://example.invalid/jwb-reference'},claims={};
claims[properties.string]=[statement(properties.string,'string',string(expected.string),{qualifiers:{[properties.qualifier]:[snak(properties.qualifier,'string',string(expected.qualifier))]},references:[{snaks:{[properties.reference]:[snak(properties.reference,'url',string(expected.reference))]},'snaks-order':[properties.reference]}]})];
claims[properties.externalId]=[statement(properties.externalId,'external-id',string(expected.externalId))];claims[properties.item]=[statement(properties.item,'wikibase-item',{value:{'entity-type':'item','numeric-id':Number(targetItem.slice(1)),id:targetItem},type:'wikibase-entityid'})];claims[properties.quantity]=[statement(properties.quantity,'quantity',{value:{amount:expected.quantity,unit:'1'},type:'quantity'})];claims[properties.time]=[statement(properties.time,'time',{value:{time:expected.time,timezone:0,before:0,after:0,precision:11,calendarmodel:'http://www.wikidata.org/entity/Q1985727'},type:'time'})];
const subjectItem=await create('item',{labels:terms('意味試験項目','Semantic fixture item'),descriptions:terms('有界意味試験','Bounded semantic qualification'),aliases:{ja:[{language:'ja',value:'意味fixture'}],en:[{language:'en',value:'semantic fixture'}]},claims});await edit(properties.string,{labels:terms('更新済み意味文字列','Updated semantic string')});
const manifest=validateSemanticFixtureManifest({version:1,fixtureType:'jwb-semantic-fixture-v1',subjectItem,targetItem,properties,expected});await writeFile(manifestPath,`${JSON.stringify(manifest,null,2)}\n`,{mode:0o600,flag:'wx'});process.stdout.write(`${JSON.stringify(manifest)}\n`);
function terms(ja,en){return{ja:{language:'ja',value:ja},en:{language:'en',value:en}};}function string(value){return{value,type:'string'};}function snak(property,datatype,datavalue){return{snaktype:'value',property,datatype,datavalue};}function statement(property,datatype,datavalue,extra={}){return{type:'statement',rank:'normal',mainsnak:snak(property,datatype,datavalue),...extra};}
async function login(){let r=await api({action:'query',meta:'tokens',type:'login'});r=await api({action:'login',lgname:adminUser,lgpassword:adminPassword,lgtoken:r.data.query.tokens.logintoken},r.cookie,true);if(r.data.login?.result!=='Success')throw new Error('JWB_SEMANTIC_LOGIN_FAILED');const csrf=await api({action:'query',meta:'tokens'},r.cookie);return{cookie:csrf.cookie,token:csrf.data.query.tokens.csrftoken};}
async function create(kind,data){const r=await api({action:'wbeditentity',new:kind,token:session.token,data:JSON.stringify(data),summary:'U1-B bounded semantic fixture'},session.cookie,true),id=r.data.entity?.id;if(!/^[QP][1-9][0-9]*$/u.test(id))throw new Error('JWB_SEMANTIC_ENTITY_CREATE_FAILED');return id;}async function edit(id,data){const r=await api({action:'wbeditentity',id,token:session.token,data:JSON.stringify(data),summary:'U1-B property schema mutation'},session.cookie,true);if(!r.data.entity?.lastrevid)throw new Error('JWB_SEMANTIC_ENTITY_EDIT_FAILED');}
async function api(parameters,cookie='',post=false){const values={format:'json',formatversion:'2',...parameters},response=post?await fetch(`${base}/api.php`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',cookie},body:new URLSearchParams(values)}):await fetch(`${base}/api.php?${new URLSearchParams(values)}`,{headers:cookie?{cookie}:{}});if(!response.ok)throw new Error(`JWB_SEMANTIC_HTTP_${response.status}`);const cookies=new Map(cookie.split('; ').filter(Boolean).map(v=>[v.split('=',1)[0],v]));for(const value of response.headers.getSetCookie?.()??[]){const pair=value.split(';',1)[0];cookies.set(pair.split('=',1)[0],pair);}return{data:await response.json(),cookie:[...cookies.values()].join('; ')};}
function trustedUrl(value){const url=new URL(value??'');if(url.protocol!=='http:'||!/^wikibase(?:\.[a-z0-9-]+\.svc\.cluster\.local)?$/u.test(url.hostname)||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw new Error('JWB_FIXTURE_SOURCE_URL_INVALID');return url.toString().replace(/\/$/u,'');}
