profile: none

images:
  core:
    repository: japan-wikibase/core
    tag: u1a-dbd16ac-amd64
    digest: sha256:fcdf50b720fb42984103fac094ae575db8f8947989ea1633f0ddeb435f168524
    pullPolicy: Never

canonicalPublicUrl: https://custom-qualification-01.wb.utirik.lodac.nii.ac.jp
trustedInternalSourceUrl: http://wikibase.wb-custom-qualification-01.svc.cluster.local
publicQueryUrl: null
siteName: Custom Wikibase Qualification 01
timezone: Asia/Tokyo

storage:
  className: local-path
  mariadb: 2Gi
  uploads: 1Gi
  runtimeState: 256Mi

resources:
  core:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}
  jobRunner:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
  mariadb:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false

networkPolicy:
  enabled: true
