profile: virtuoso
queryExistingSecret: custom-wikibase-query-secrets

images:
  core:
    repository: japan-wikibase/core
    tag: u1a-dbd16ac-amd64
    digest: sha256:fcdf50b720fb42984103fac094ae575db8f8947989ea1633f0ddeb435f168524
    pullPolicy: Never

canonicalPublicUrl: https://custom-qualification-01.wb.utirik.lodac.nii.ac.jp
trustedInternalSourceUrl: http://wikibase.wb-custom-qualification-01.svc.cluster.local
publicQueryUrl: https://query-custom-qualification-01.wb.utirik.lodac.nii.ac.jp/sparql
siteName: Custom Wikibase Qualification 01
timezone: Asia/Tokyo

identities:
  instanceId: a622a3e7-ff84-46bf-bf41-88410024e183
  sourceIdentity: custom-wikibase.a622a3e7-ff84-46bf-bf41-88410024e183
  queryServiceId: custom-wikibase-query-a622a3e7-ff84-46bf-bf41-88410024e183

storage:
  className: local-path
  mariadb: 2Gi
  uploads: 1Gi
  runtimeState: 256Mi
  postgresql: 1Gi
  virtuoso: 2Gi
  snapshots: 1Gi

resources:
  core:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}
  jobRunner:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
  mariadb:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}
  runtime:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
  postgresql:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: "1", memory: 1Gi}
  virtuoso:
    requests: {cpu: 250m, memory: 512Mi}
    limits: {cpu: "2", memory: 2Gi}

podSecurityContext:
  seccompProfile: {type: RuntimeDefault}
containerSecurityContext:
  allowPrivilegeEscalation: false
networkPolicy:
  enabled: true
ingress:
  enabled: true
  className: traefik
  hostname: custom-qualification-01.wb.utirik.lodac.nii.ac.jp
  clusterIssuer: letsencrypt-staging
  tlsSecretName: custom-qualification-01-tls
  queryHostname: query-custom-qualification-01.wb.utirik.lodac.nii.ac.jp
  queryTlsSecretName: query-custom-qualification-01-tls
  bodyLimitBytes: 10485760
  bodyMemoryBytes: 2097152
  rateLimitAverage: 120
  rateLimitBurst: 60
