import assert from 'node:assert/strict';
import test from 'node:test';
import { TrustedGenerationResolver, deriveTarget } from './generation-resolver.js';

const valid = generationId => ({ sourceIdentity:'jwb-local',generationId,backendType:'virtuoso',state:'SERVING',protectionState:'SERVING',normalizationModel:'jwb-rdf-normalization-v1',partitionModel:'jwb-partition-v1',runtimeType:'kubernetes',namespace:'jwb-query-local' });
test('trusted resolver derives arbitrary generation endpoint and invalidates by pointer version',async()=>{let calls=0;const repository={async getDescriptor({generationId}){calls++;return valid(generationId);}},resolver=new TrustedGenerationResolver({generationRepository:repository,runtimeType:'kubernetes'});const a=await resolver.resolve({sourceIdentity:'jwb-local',generationId:'gen-c',version:3});assert.equal(a.queryUrl,'http://rdf-virtuoso-gen-c.jwb-query-local.svc.cluster.local:8890/sparql');await resolver.resolve({sourceIdentity:'jwb-local',generationId:'gen-c',version:3});assert.equal(calls,1);await resolver.resolve({sourceIdentity:'jwb-local',generationId:'gen-d',version:4});assert.equal(calls,2);});
test('descriptor failures are fail closed',()=>{for(const patch of [{backendType:'unknown'},{namespace:'production'},{state:'FAILED'},{protectionState:'NONE'},{sourceIdentity:'other'},{normalizationModel:'other'}])assert.throws(()=>deriveTarget({...valid('gen-c'),...patch},{expectedSourceIdentity:'jwb-local',runtimeType:'kubernetes'}),/ROUTER_TARGET_UNRESOLVABLE/u);});
test('router accepts only exact stable and protected rollback lifecycle pairs',()=>{for(const descriptor of [{...valid('gen-a'),state:'READY',protectionState:'NONE'},{...valid('gen-a'),state:'RETIRING',protectionState:'ROLLBACK'}])assert.equal(deriveTarget(descriptor,{expectedSourceIdentity:'jwb-local',runtimeType:'kubernetes'}).queryUrl.includes('gen-a'),true);for(const descriptor of [{...valid('gen-a'),state:'RETIRING',protectionState:'NONE'},{...valid('gen-a'),state:'READY',protectionState:'ROLLBACK'}])assert.throws(()=>deriveTarget(descriptor,{expectedSourceIdentity:'jwb-local',runtimeType:'kubernetes'}),/ROUTER_TARGET_UNRESOLVABLE/u);});
test('standalone resolver maps only fixed A/B slots to private service DNS',()=>{const descriptor={...valid('gen-a'),sourceIdentity:'jwb-standalone',runtimeType:'compose',namespace:null};assert.deepEqual(deriveTarget(descriptor,{expectedSourceIdentity:'jwb-standalone',runtimeType:'standalone-compose'}),{queryUrl:'http://backend-a:8890/sparql',healthUrl:'http://backend-a:8890/sparql',allowedHostname:'backend-a'});assert.throws(()=>deriveTarget({...descriptor,generationId:'gen-c'},{expectedSourceIdentity:'jwb-standalone',runtimeType:'standalone-compose'}),/ROUTER_TARGET_UNRESOLVABLE/u);});
