import assert from'node:assert/strict';import test from'node:test';import{QueryRouter}from'./router.js';import{RouterMetrics}from'./metrics.js';import{validateReadOnlySparql}from'./query-policy.js';import{TrustedGenerationResolver}from'./generation-resolver.js';
class Pointer{constructor(){this.value={sourceIdentity:'jwb-local',generationId:'gen-a',version:1};}async get(){return{...this.value};}promote(generationId,expected){if(expected!==this.value.version)throw new Error('CONFLICT');this.value={...this.value,generationId,version:expected+1};}}
const descriptors=new Map(['gen-a','gen-b','gen-c','gen-durable-4'].map(generationId=>[generationId,{sourceIdentity:'jwb-local',generationId,backendType:'virtuoso',runtimeType:'kubernetes',namespace:'jwb-query-local',state:'SERVING',normalizationModel:'jwb-rdf-normalization-v1',partitionModel:'jwb-partition-v1'}]));
const repository={async getDescriptor({generationId}){return descriptors.get(generationId)??null;}};
const resolver=()=>new TrustedGenerationResolver({generationRepository:repository,runtimeType:'kubernetes'});
const fetchImpl=async url=>new Response(JSON.stringify({marker:url.hostname}),{status:200,headers:{'content-type':'application/sparql-results+json'}});
test('policy accepts query forms and rejects updates, SERVICE and oversized input',()=>{assert.equal(validateReadOnlySparql('SELECT * WHERE { ?s ?p "DELETE" }'),'SELECT * WHERE { ?s ?p "DELETE" }');for(const q of['INSERT DATA {}','SELECT * WHERE { SERVICE <http://x> {} }','DROP ALL'])assert.throws(()=>validateReadOnlySparql(q),/FORBIDDEN|INVALID/u);assert.throws(()=>validateReadOnlySparql('ASK{}'.repeat(20000)),/SIZE/u);});
test('two routers resolve A -> B -> C -> arbitrary D at request boundaries',async()=>{const pointer=new Pointer(),metricsA=new RouterMetrics(),metricsB=new RouterMetrics(),a=new QueryRouter({pointerRepository:pointer,generationResolver:resolver(),metrics:metricsA,fetchImpl}),b=new QueryRouter({pointerRepository:pointer,generationResolver:resolver(),metrics:metricsB,fetchImpl});for(const id of ['gen-a','gen-b','gen-c','gen-durable-4']){if(id!==pointer.value.generationId)pointer.promote(id,pointer.value.version);const results=await Promise.all([a.query('ASK {}'),b.query('ASK {}')]);for(const result of results)assert.equal(JSON.parse(new TextDecoder().decode(result.body)).marker,`rdf-virtuoso-${id}.jwb-query-local.svc.cluster.local`);}assert.equal(metricsA.values.get('serving_pointer_reload_total'),4);assert.equal(metricsB.values.get('serving_pointer_reload_total'),4);});
test('stale CAS and missing descriptor fail closed',async()=>{const pointer=new Pointer();assert.throws(()=>pointer.promote('gen-b',0),/CONFLICT/u);pointer.value={...pointer.value,generationId:'gen-unknown',version:2};const router=new QueryRouter({pointerRepository:pointer,generationResolver:resolver(),metrics:new RouterMetrics(),fetchImpl});await assert.rejects(router.query('ASK {}'),/ROUTER_TARGET_UNRESOLVABLE/u);});
test('logical dataset is supplied as validated SPARQL Protocol default graphs',async()=>{const pointer=new Pointer();pointer.value={...pointer.value,graphIris:['urn:jwb:entity:Q1','urn:jwb:schema:P1','urn:jwb:global']};let observedParams=[];const router=new QueryRouter({pointerRepository:pointer,generationResolver:resolver(),metrics:new RouterMetrics(),fetchImpl:async url=>{observedParams=url.searchParams.getAll('default-graph-uri');return new Response('{"boolean":true}',{headers:{'content-type':'application/sparql-results+json'}});}});await router.query('ASK {}');assert.deepEqual(observedParams,pointer.value.graphIris);pointer.value.graphIris=['https://attacker.invalid/graph'];await assert.rejects(router.query('ASK {}'),/SERVING_GRAPH_INVALID/u);});
