import{performance}from'node:perf_hooks';import{validateReadOnlySparql}from'./query-policy.js';
export class QueryRouter{
  /** @param {{pointerRepository:any,generationResolver?:any,targetRegistry?:Iterable<[string,any]>,metrics:any,fetchImpl?:typeof fetch,timeoutMs?:number,maxRequestBytes?:number,maxResponseBytes?:number}} options */
  constructor({pointerRepository,generationResolver,targetRegistry,metrics,fetchImpl=fetch,timeoutMs=10000,maxRequestBytes=65536,maxResponseBytes=5_000_000}){if(!generationResolver&&!targetRegistry)throw new Error('generation resolver is required');this.pointerRepository=pointerRepository;this.generationResolver=generationResolver??staticQualificationResolver(/** @type {Iterable<[string,any]>} */(targetRegistry));this.metrics=metrics;this.fetchImpl=fetchImpl;this.timeoutMs=timeoutMs;this.maxRequestBytes=maxRequestBytes;this.maxResponseBytes=maxResponseBytes;this.lastPointer=null;}
  async ready(){try{const pointer=await this.#pointer(),target=await this.generationResolver.resolve(pointer),health=await this.#fetch(target.healthUrl,target.allowedHostname,{method:'POST',headers:{accept:'application/sparql-results+json','content-type':'application/sparql-query'},body:'ASK { ?s ?p ?o }'});return health.ok;}catch{return false;}}
  async query(sparql,accept='application/sparql-results+json'){const started=performance.now();this.metrics.increment('queries_total');try{validateReadOnlySparql(sparql,{maxBytes:this.maxRequestBytes});const pointer=await this.#pointer(),target=await this.generationResolver.resolve(pointer),queryUrl=logicalDatasetUrl(target.queryUrl,pointer.graphIris),upstreamStarted=performance.now(),response=await this.#fetch(queryUrl,target.allowedHostname,{method:'POST',headers:{accept:allowedAccept(accept),'content-type':'application/sparql-query'},body:sparql});this.metrics.set('upstream_latency_ms',performance.now()-upstreamStarted);if(!response.ok)throw new Error('UPSTREAM_QUERY_FAILED');const declared=Number(response.headers.get('content-length')??0);if(declared>this.maxResponseBytes)throw new Error('UPSTREAM_RESPONSE_TOO_LARGE');const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength>this.maxResponseBytes)throw new Error('UPSTREAM_RESPONSE_TOO_LARGE');this.metrics.activeGeneration=pointer.generationId;this.metrics.set('pointer_version',pointer.version);return{status:200,body:bytes,contentType:response.headers.get('content-type')??allowedAccept(accept),generationId:pointer.generationId,pointerVersion:pointer.version};}catch(error){this.metrics.increment('query_failures_total');throw new Error(code(error));}finally{this.metrics.set('router_latency_ms',performance.now()-started);}}
  async #pointer(){const pointer=await this.pointerRepository.get();if(!this.lastPointer||pointer.version!==this.lastPointer.version)this.metrics.increment('serving_pointer_reload_total');this.lastPointer=pointer;return pointer;}
  async #fetch(url,allowedHostname,init){const target=new URL(url);if(target.protocol!=='http:'||target.hostname!==allowedHostname)throw new Error('ROUTER_TARGET_UNRESOLVABLE');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{return await this.fetchImpl(target,{...init,signal:controller.signal});}finally{clearTimeout(timer);}}
}
function allowedAccept(v){return['application/sparql-results+json','application/n-triples'].includes(v)?v:'application/sparql-results+json';}
function code(error){return String(error?.message??'ROUTER_FAILURE').match(/[A-Z][A-Z0-9_]{2,63}/u)?.[0]??'ROUTER_FAILURE';}
function logicalDatasetUrl(value,graphIris){const url=new URL(value);for(const graphIri of graphIris??[]){if(!/^urn:jwb:(?:entity:[QP][1-9][0-9]*|schema:P[1-9][0-9]*|global)$/u.test(graphIri))throw new Error('SERVING_GRAPH_INVALID');url.searchParams.append('default-graph-uri',graphIri);}return url;}
function staticQualificationResolver(entries){const targets=new Map(entries);return{resolve:async pointer=>{const target=targets.get(pointer.generationId);if(!target)throw new Error('ROUTER_TARGET_UNRESOLVABLE');return{...target,allowedHostname:new URL(target.queryUrl).hostname};}};}
