#!/usr/bin/env node
import{execFileSync,spawn}from'node:child_process';import{randomBytes,randomUUID,createHash}from'node:crypto';import{existsSync,readFileSync,writeFileSync,chmodSync,unlinkSync}from'node:fs';import{parseBackend,composeFiles,writeProfile,readProfile,JWB_PRODUCT_PROJECT,JWB_PRODUCT_STATE}from'./jwb-product-lib.mjs';import{validateJwbRuntimeV1}from'../packages/runtime-contract/src/validate.js';
const action=process.argv[2],root=new URL('../infrastructure/japan-wikibase/',import.meta.url).pathname,file=`${root}compose.product.yaml`,runtimeFile='/private/tmp/japan-wikibase-runtime.json',base='http://127.0.0.1:8280';if(!['create','status','stop','start','test','destroy','select','recreate-app','recreate-query','promote','rollback','rebuild','restart-candidate-worker','restart-candidate-backend','restart-serving-backend','restart-postgresql','validate-candidate','validate-serving'].includes(action))fail('usage: create|status|stop|start|test|destroy|select|rebuild|promote|rollback');
if(action==='select'){const backend=parseBackend(process.argv.slice(3));writeProfile(backend);output({project:JWB_PRODUCT_PROJECT,backend});process.exit(0);}assertDocker();if(action==='create')create();if(action==='status')await status();if(action==='stop')stop();if(action==='start')start();if(action==='test')await qualify();if(action==='destroy')destroy();if(action==='recreate-app')recreateApp();if(action==='recreate-query')recreateQuery();if(action==='promote')lifecycle('promote');if(action==='rollback')lifecycle('rollback');if(action==='rebuild')await rebuild();if(action==='restart-candidate-worker')restartCandidate('worker');if(action==='restart-candidate-backend')restartCandidate('backend');if(action==='restart-serving-backend')restartServingBackend();if(action==='restart-postgresql')restartPostgresql();if(action==='validate-candidate')await validateCandidate();if(action==='validate-serving')await validateServing();
function create(){const backend=parseBackend(process.argv.slice(3));if(!isProductBackend(backend))fail('product profile is not qualified yet');if(existsSync(runtimeFile)||existsSync(JWB_PRODUCT_STATE))fail('product state already exists');const state={schemaVersion:1,project:JWB_PRODUCT_PROJECT,instanceId:randomUUID(),databaseName:'japan_wikibase',databaseUser:'jwb_app',databasePassword:secret(),databaseRootPassword:secret(),adminUser:'JwbAdmin',adminPassword:secret(),secretKey:secret(48),upgradeKey:secret(),queryDatabasePassword:secret(),rdfAdminPassword:secret(),entityId:null,uploadName:null,uploadChecksum:null};writeRuntime(state);writeProfile(backend);compose(['up','--detach','--build','--wait','--wait-timeout','900'],state);output({project:JWB_PRODUCT_PROJECT,backend,url:base,queryUrl:backend==='none'?null:'http://127.0.0.1:8290/sparql',instanceId:state.instanceId});}
async function status(){
  const state=readRuntime(),profile=readProfile(),rows=ps(state),names=profile.backend==='none'?['mariadb','wikibase','job-runner']:['mariadb','wikibase','job-runner','jwb-postgresql','jwb-migrate','jwb-bootstrap','rdf-source-reader','rdf-sync-worker','rdf-sync-worker-b','query-router','backend-a','backend-b'];
  const services=Object.fromEntries(names.map(name=>{const row=rows.find(value=>value.Service===name);return[name,{running:row?.State==='running',health:row?.Health||null,state:row?.State??'absent'}];}));
  let discovery=null,site=null,candidate=null,lifecycleState=null;
  try{discovery=validateJwbRuntimeV1(await getJson('/.well-known/japan-wikibase-runtime'));}catch{}
  try{site=await getJson('/api.php?action=query&meta=siteinfo&format=json&formatversion=2');}catch{}
  if(isQueryBackend(profile.backend)&&services['jwb-postgresql'].running){try{candidate=coordinator(state,'observe');}catch{}try{lifecycleState=JSON.parse(composeCapture(['exec','--no-TTY','query-router','node','packages/jwb-database/src/jwb-lifecycle-cli.js','status'],state).split('\n').at(-1));}catch{}}
  const serving=lifecycleState?.generations?.find(value=>value.generationId===lifecycleState.pointer.generationId),rollback=lifecycleState?.generations?.find(value=>value.generationId===lifecycleState.pointer.previousGenerationId);
  output({project:JWB_PRODUCT_PROJECT,backend:profile.backend,instanceId:state.instanceId,mediaWiki:{healthy:Boolean(site?.query?.general?.generator),version:site?.query?.general?.generator??null},actionApi:{healthy:Boolean(site?.query)},services,querySubsystem:profile.backend==='none'?'disabled':'enabled',runtimeContract:discovery?{contractVersion:discovery.contractVersion,distributionVersion:discovery.distribution.version,health:discovery.health.state,instanceId:discovery.instance.id,queryEnabled:discovery.queryService.enabled,servingGeneration:discovery.queryService.servingGeneration??null,syncState:discovery.queryService.syncState??null,freshness:discovery.queryService.freshness??null}:null,lifecycle:lifecycleState?{pointerVersion:lifecycleState.pointer.version,servingGeneration:lifecycleState.pointer.generationId,rollbackGeneration:lifecycleState.pointer.previousGenerationId,servingState:serving??null,rollbackState:rollback??null,lastPromotion:lifecycleState.lastPromotion}:null,candidate:candidate?{servingGeneration:candidate.servingGeneration,candidateGeneration:candidate.candidateGeneration,lifecycleState:candidate.candidateState,syncState:candidate.syncState,schemaState:candidate.schemaState,validationStatus:candidate.candidateValidation,activeRebuild:candidate.activeRebuild,syncLagSeconds:candidate.syncLagSeconds,sourceIdleSeconds:candidate.sourceIdleSeconds,partitionCounts:candidate.partitionCounts}:null});
}
function stop(){const state=readRuntime();compose(['stop'],state);output({project:JWB_PRODUCT_PROJECT,state:'stopped',volumesRetained:true});}function start(){const state=readRuntime();compose(['up','--detach','--wait','--wait-timeout','300','--no-build'],state);output({project:JWB_PRODUCT_PROJECT,state:'running'});}
function recreateApp(){const state=readRuntime();compose(['up','--detach','--build','--force-recreate','--wait','--wait-timeout','900','wikibase','job-runner'],state);output({project:JWB_PRODUCT_PROJECT,state:'application-recreated'});}
function recreateQuery(){const state=readRuntime(),profile=readProfile();if(!isQueryBackend(profile.backend))fail('query recreation requires a qualified query backend');compose(['up','--detach','--build','--force-recreate','--wait','--wait-timeout','900','rdf-source-reader','rdf-sync-worker','rdf-sync-worker-b','query-router'],state);output({project:JWB_PRODUCT_PROJECT,state:'query-runtime-recreated'});}
function lifecycle(operation){const state=readRuntime(),profile=readProfile(),crash=process.env.JWB_PROMOTION_CRASH_AT;if(!isQueryBackend(profile.backend)||process.argv.length!==3||crash&&!['BEFORE_POINTER_CAS','AFTER_POINTER_CAS'].includes(crash))fail('lifecycle operation requires a fixed qualified query profile and bounded crash point');const crashArgs=crash?['--env',`JWB_PROMOTION_CRASH_AT=${crash}`]:[];compose(['exec','--no-TTY',...crashArgs,'query-router','node','packages/jwb-database/src/jwb-lifecycle-cli.js',operation],state);}
function restartCandidate(kind){const state=readRuntime();if(!isQueryBackend(readProfile().backend))fail('candidate restart requires a qualified query backend');const selected=coordinator(state,'inspect'),service=kind==='worker'?(selected.candidateGeneration==='gen-a'?'rdf-sync-worker':'rdf-sync-worker-b'):(selected.candidateGeneration==='gen-a'?'backend-a':'backend-b');compose(['up','--detach','--no-deps','--force-recreate','--wait','--wait-timeout','300',service],state);output({candidateGeneration:selected.candidateGeneration,restarted:kind,service});}
function restartServingBackend(){const state=readRuntime();if(!isQueryBackend(readProfile().backend)||process.argv.length!==3)fail('serving backend restart requires a qualified query backend');const selected=coordinator(state,'inspect'),service=selected.servingGeneration==='gen-a'?'backend-a':'backend-b';compose(['up','--detach','--no-deps','--force-recreate','--wait','--wait-timeout','300',service],state);output({servingGeneration:selected.servingGeneration,restarted:'backend',service});}
function restartPostgresql(){const state=readRuntime();if(!isQueryBackend(readProfile().backend)||process.argv.length!==3)fail('PostgreSQL restart requires a qualified query backend');compose(['up','--detach','--no-deps','--force-recreate','--wait','--wait-timeout','300','jwb-postgresql'],state);output({restarted:'jwb-postgresql',volumeRetained:true});}
async function validateCandidate(){const state=readRuntime();if(!isQueryBackend(readProfile().backend))fail('candidate validation requires a qualified query backend');const snapshotId=randomUUID(),cursor=await latestCursor();runSnapshot(state,snapshotId,cursor);const result=coordinator(state,'validate',snapshotId);if(result.missing||result.extra||result.validation!=='VALID')fail(`candidate validation failed:${result.missing}:${result.extra}`);output({candidateGeneration:result.candidateGeneration,state:result.candidateState,validation:result.validation,missing:0,extra:0,partitionCounts:result.partitionCounts});}
async function validateServing(){const state=readRuntime();if(!isQueryBackend(readProfile().backend)||process.argv.length!==3)fail('serving validation requires a fixed qualified query profile');let result=null,lastError=null;for(let attempt=0;attempt<10;attempt++){const snapshotId=randomUUID(),cursor=await latestCursor();runSnapshot(state,snapshotId,cursor);try{result=coordinator(state,'validate-serving',snapshotId);if(!result.missing&&!result.extra&&result.validation==='VALID')break;}catch(error){lastError=error;const detail=String(error)+(error.stderr??'');if(!detail.includes('SERVING_NOT_CURRENT'))throw error;}await new Promise(resolve=>setTimeout(resolve,1000));}if(!result||result.missing||result.extra||result.validation!=='VALID')fail(`serving validation failed:${result?.missing??'unknown'}:${result?.extra??'unknown'}:${lastError?'not-current':''}`);output(result);}
async function rebuild(){const state=readRuntime(),profile=readProfile();if(!isQueryBackend(profile.backend))fail('rebuild requires a qualified query backend');if(process.argv.length!==3)fail('rebuild accepts no arguments');const selected=coordinator(state,'inspect'),worker=selected.candidateGeneration==='gen-a'?'rdf-sync-worker':'rdf-sync-worker-b';compose(['stop',worker],state);try{const initial=await latestCursor(),snapshotId=randomUUID(),raceTest=process.env.JWB_REBUILD_RACE_TEST==='true';let raceRevision=null;if(raceTest){const producing=runSnapshotAsync(state,snapshotId,initial);let dumpComplete=false;for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>setTimeout(resolve,500));dumpComplete=coordinator(state,'phase',snapshotId).dumpComplete;if(dumpComplete)break;}if(!dumpComplete)fail('snapshot dump phase timeout');raceRevision=await controlledSnapshotEdit(state);await producing;}else runSnapshot(state,snapshotId,initial);const loaded=coordinator(state,'load',snapshotId),target=await latestCursor();compose(['up','--detach','--no-deps',worker],state);let observed=null;for(let attempt=0;attempt<120;attempt++){observed=coordinator(state,'observe');if(observed.readyForValidation&&cursorAtLeast(observed.catchupCursor,target))break;await new Promise(resolve=>setTimeout(resolve,1000));}if(!observed?.readyForValidation||!cursorAtLeast(observed.catchupCursor,target))fail('candidate catch-up timeout');const referenceId=randomUUID(),referenceCursor=await latestCursor();runSnapshot(state,referenceId,referenceCursor);const validated=coordinator(state,'validate',referenceId);if(validated.missing!==0||validated.extra!==0||validated.validation!=='VALID'){writeFileSync('/private/tmp/jwb-j2c1a-difference.json',`${JSON.stringify({sourceCursor:initial,targetCursor:target,candidateCursor:observed.catchupCursor,raceRevision,...validated},null,2)}\n`,{mode:0o600});fail(`candidate canonical equality failed:${validated.missing}:${validated.extra}`);}output({project:JWB_PRODUCT_PROJECT,backend:profile.backend,servingGeneration:selected.servingGeneration,candidateGeneration:selected.candidateGeneration,snapshotId,sourceCursor:initial,targetCursor:target,raceRevision,editDuringSnapshot:raceTest,loadedGraphs:loaded.graphCount,catchup:{state:observed.syncState,schemaState:observed.schemaState,cursor:observed.catchupCursor},canonicalEquality:{missing:validated.missing,extra:validated.extra,normalizationModel:validated.normalizationModel,partitionModel:validated.partitionModel},candidateState:'READY',promoted:false});}catch(error){compose(['up','--detach','--no-deps',worker],state);throw error;}}
async function qualify(){
  const state=readRuntime(),profile=readProfile();
  if(!isProductBackend(profile.backend))fail('product profile is not qualified');
  const site=await getJson('/api.php?action=query&meta=siteinfo&siprop=general%7Cextensions&format=json&formatversion=2');
  if(site.query?.general?.lang!=='ja'||!site.query.extensions.some(v=>v.name==='WikibaseRepository'))fail('MediaWiki/Wikibase health failed');
  const session=await login(state);
  if(!state.entityId){const csrf=await token(session.cookie),created=await post({action:'wbeditentity',new:'item',token:csrf,data:JSON.stringify({labels:{ja:{language:'ja',value:'Japan Wikibase 製品適合項目'},en:{language:'en',value:'Japan Wikibase product fixture'}},descriptions:{ja:{language:'ja',value:'永続性とRDF同期の確認'}}})},session.cookie);state.entityId=created.entity?.id;if(!state.entityId)fail('entity creation failed');writeRuntime(state);}
  if(isQueryBackend(profile.backend)&&!state.queryPropertyId){const csrf=await token(session.cookie),created=await post({action:'wbeditentity',new:'property',token:csrf,data:JSON.stringify({datatype:'string',labels:{ja:{language:'ja',value:'J2-C 文字列プロパティ'},en:{language:'en',value:'J2-C string property'}}})},session.cookie);state.queryPropertyId=created.entity?.id;if(!state.queryPropertyId)fail('property creation failed');writeRuntime(state);}
  const entity=await getJson(`/api.php?action=wbgetentities&ids=${state.entityId}&languages=ja&format=json&formatversion=2`);if(!entity.entities?.[state.entityId]||entity.entities[state.entityId].missing!==undefined)fail('entity persistence failed');
  const fixture=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'),fixtureChecksum=createHash('sha256').update(fixture).digest('hex');
  if(!state.uploadName){const csrf=await token(session.cookie),form=new FormData();for(const [k,v]of Object.entries({action:'upload',filename:'J2B-Core-Fixture.png',comment:'Japan Wikibase generated fixture',ignorewarnings:'1',token:csrf,format:'json',formatversion:'2'}))form.set(k,v);form.set('file',new Blob([fixture],{type:'image/png'}),'J2B-Core-Fixture.png');const response=await fetch(`${base}/api.php`,{method:'POST',headers:{cookie:session.cookie},body:form}),data=await response.json(),alreadyExists=data.error?.code==='fileexists-no-change';if(data.upload?.result!=='Success'&&!alreadyExists)fail(`upload failed:${data.error?.code??data.upload?.result}`);state.uploadName=data.upload?.filename??'J2B-Core-Fixture.png';state.uploadChecksum=fixtureChecksum;writeRuntime(state);}
  const info=await getJson(`/api.php?action=query&titles=File:${encodeURIComponent(state.uploadName)}&prop=imageinfo&iiprop=url&format=json&formatversion=2`),url=info.query.pages[0].imageinfo?.[0]?.url;if(!url)fail('upload metadata missing');const bytes=Buffer.from(await(await fetch(url)).arrayBuffer()),checksum=createHash('sha256').update(bytes).digest('hex');if(checksum!==state.uploadChecksum)fail('upload checksum changed');
  let contract=validateJwbRuntimeV1(await getJson('/.well-known/japan-wikibase-runtime'));
  if(isQueryBackend(profile.backend)){for(let attempt=0;attempt<90&&contract.queryService.syncState!=='CURRENT';attempt++){await new Promise(resolve=>setTimeout(resolve,2000));contract=validateJwbRuntimeV1(await getJson('/.well-known/japan-wikibase-runtime'));}if(contract.queryService.enabled!==true||contract.queryService.backendType!==profile.backend||contract.queryService.syncState!=='CURRENT')fail('query backend synchronization did not become current');const result=await sparql(`ASK { ?entity <http://www.w3.org/2000/01/rdf-schema#label> "Japan Wikibase 製品適合項目"@ja }`);if(result.boolean!==true)fail('logical SPARQL fixture missing');}else if(contract.queryService.enabled!==false)fail('Core runtime contract mismatch');
  if(contract.instance.id!==state.instanceId)fail('runtime contract identity mismatch');writeRuntime(state);output({project:JWB_PRODUCT_PROJECT,backend:profile.backend,mediaWiki:site.query.general.generator,wikibaseRevision:'c79eb4efab9ad27267a6df9034e1b99ad695d1c7',language:'ja',timezone:'Asia/Tokyo',entityId:state.entityId,propertyId:state.queryPropertyId??null,uploadName:state.uploadName,uploadChecksum:state.uploadChecksum,instanceId:state.instanceId,servingGeneration:contract.queryService.servingGeneration??null,syncState:contract.queryService.syncState??null,runtimeContract:'valid'});
}
async function sparql(query){const response=await fetch('http://127.0.0.1:8290/sparql',{method:'POST',headers:{accept:'application/sparql-results+json','content-type':'application/sparql-query'},body:query});if(!response.ok)fail(`logical SPARQL HTTP ${response.status}`);return response.json();}
function destroy(){if(!existsSync(runtimeFile)&&!existsSync(JWB_PRODUCT_STATE)){output({project:JWB_PRODUCT_PROJECT,state:'absent'});return;}const state=readRuntime(),profile=readProfile();if(!isProductBackend(profile.backend))fail('destroy refuses an unqualified profile');compose(['--profile','snapshot','down','--volumes','--remove-orphans'],state);unlinkSync(runtimeFile);unlinkSync(JWB_PRODUCT_STATE);const fixture='/private/tmp/japan-wikibase-semantic-fixture.json';if(existsSync(fixture))unlinkSync(fixture);output({project:JWB_PRODUCT_PROJECT,state:'destroyed'});}
function isQueryBackend(value){return ['virtuoso','fuseki-tdb2','oxigraph'].includes(value);}
function isProductBackend(value){return value==='none'||isQueryBackend(value);}
function readRuntime(){if(!existsSync(runtimeFile))fail('runtime state missing');const value=JSON.parse(readFileSync(runtimeFile,'utf8'));if(value.schemaVersion!==1||value.project!==JWB_PRODUCT_PROJECT||!/^[0-9a-f-]{36}$/u.test(value.instanceId))fail('runtime state invalid');return value;}function writeRuntime(value){writeFileSync(runtimeFile,`${JSON.stringify(value)}\n`,{mode:0o600});chmodSync(runtimeFile,0o600);}function secret(n=36){return randomBytes(n).toString('base64url');}function cursorAtLeast(actual,target){const a=Date.parse(actual.timestamp),t=Date.parse(target.timestamp);return a>t||a===t&&actual.rcid>=target.rcid;}
function env(s){return{...process.env,DOCKER_CONTEXT:'desktop-linux',JWB_DB_NAME:s.databaseName,JWB_DB_USER:s.databaseUser,JWB_DB_PASSWORD:s.databasePassword,JWB_DB_ROOT_PASSWORD:s.databaseRootPassword,JWB_ADMIN_USER:s.adminUser,JWB_ADMIN_PASSWORD:s.adminPassword,JWB_SECRET_KEY:s.secretKey,JWB_UPGRADE_KEY:s.upgradeKey,JWB_INSTANCE_ID:s.instanceId,JWB_QUERY_DB_PASSWORD:s.queryDatabasePassword,JWB_RDF_ADMIN_PASSWORD:s.rdfAdminPassword,JWB_QUERY_BACKEND:readProfile().backend};}function composeArgs(){return composeFiles(readProfile().backend).flatMap(name=>['--file',`${root}${name}`]);}function compose(args,s){execFileSync('docker',['compose','--project-name',JWB_PRODUCT_PROJECT,...composeArgs(),...args],{cwd:root,env:env(s),stdio:'inherit'});}function composeCapture(args,s,extra={}){return execFileSync('docker',['compose','--project-name',JWB_PRODUCT_PROJECT,...composeArgs(),...args],{cwd:root,env:{...env(s),...extra},encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();}function coordinator(s,operation,snapshotId='00000000-0000-4000-8000-000000000010'){const text=composeCapture(['--profile','snapshot','run','--rm','--no-deps','jwb-rebuild-coordinator'],s,{JWB_REBUILD_ACTION:operation,JWB_SNAPSHOT_ID:snapshotId});return JSON.parse(text.split('\n').at(-1));}function runSnapshot(s,snapshotId,cursor){execFileSync('docker',['compose','--project-name',JWB_PRODUCT_PROJECT,...composeArgs(),'--profile','snapshot','run','--rm','--no-deps','--build','rdf-snapshot-producer'],{cwd:root,env:{...env(s),JWB_SNAPSHOT_ID:snapshotId,JWB_SNAPSHOT_CURSOR_TIMESTAMP:cursor.timestamp,JWB_SNAPSHOT_CURSOR_RCID:String(cursor.rcid)},stdio:'inherit'});}async function latestCursor(){const data=await getJson('/api.php?action=query&list=recentchanges&rcdir=older&rclimit=1&rcnamespace=120%7C122&rcprop=ids%7Ctimestamp&format=json&formatversion=2'),event=data.query?.recentchanges?.[0];return event?{timestamp:event.timestamp,rcid:Number(event.rcid)}:{timestamp:'1970-01-01T00:00:00Z',rcid:0};}function ps(s){const text=execFileSync('docker',['compose','--project-name',JWB_PRODUCT_PROJECT,...composeArgs(),'ps','--all','--format','json'],{cwd:root,env:env(s),encoding:'utf8'}).trim();return text.startsWith('[')?JSON.parse(text):text.split('\n').filter(Boolean).map(line=>JSON.parse(line));}
function runSnapshotAsync(s,snapshotId,cursor){const child=spawn('docker',['compose','--project-name',JWB_PRODUCT_PROJECT,...composeArgs(),'--profile','snapshot','run','--rm','--no-deps','--build','rdf-snapshot-producer'],{cwd:root,env:{...env(s),JWB_SNAPSHOT_ID:snapshotId,JWB_SNAPSHOT_CURSOR_TIMESTAMP:cursor.timestamp,JWB_SNAPSHOT_CURSOR_RCID:String(cursor.rcid),JWB_SNAPSHOT_RACE_TEST:'true'},stdio:'inherit'});return new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',code=>code===0?resolve():reject(new Error(`snapshot producer exited ${code}`)));});}async function controlledSnapshotEdit(s){if(!/^Q[1-9][0-9]*$/u.test(s.entityId??''))fail('race test fixture item missing');const session=await login(s),csrf=await token(session.cookie),value=`snapshot race ${new Date().toISOString()}`,result=await post({action:'wbeditentity',id:s.entityId,token:csrf,data:JSON.stringify({aliases:{en:[{language:'en',value}]}}),summary:'J2-C1a controlled snapshot race edit'},session.cookie);if(!result.entity?.lastrevid)fail('controlled snapshot edit failed');return{entityId:s.entityId,revision:Number(result.entity.lastrevid)};}
function assertDocker(){const context=execFileSync('docker',['context','show'],{encoding:'utf8'}).trim(),info=execFileSync('docker',['info','--format','{{.OperatingSystem}}|{{.Architecture}}'],{encoding:'utf8'}).trim();if(context!=='desktop-linux'||!/Docker Desktop.*\|aarch64/u.test(info))fail(`unsafe Docker target:${context}:${info}`);}async function getJson(path){const response=await fetch(`${base}${path}`);if(!response.ok)fail(`HTTP ${response.status}`);return response.json();}async function login(s){const initial=await getSession('/api.php?action=query&meta=tokens&type=login&format=json&formatversion=2'),data=await post({action:'login',lgname:s.adminUser,lgpassword:s.adminPassword,lgtoken:initial.data.query.tokens.logintoken},initial.cookie);if(data.login?.result!=='Success')fail('login failed');return{cookie:data.cookie};}async function token(cookie){const value=await getSession('/api.php?action=query&meta=tokens&format=json&formatversion=2',cookie);return value.data.query.tokens.csrftoken;}async function getSession(path,cookie=''){const response=await fetch(`${base}${path}`,{headers:cookie?{cookie}:{}}),data=await response.json(),next=merge(cookie,response.headers.getSetCookie?.()??[]);return{data,cookie:next};}async function post(values,cookie){const response=await fetch(`${base}/api.php`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',cookie},body:new URLSearchParams({format:'json',formatversion:'2',...values})}),data=await response.json();data.cookie=merge(cookie,response.headers.getSetCookie?.()??[]);return data;}function merge(current,set){const map=new Map();for(const v of current?current.split('; '):[])map.set(v.split('=',1)[0],v);for(const v of set){const pair=v.split(';',1)[0];map.set(pair.split('=',1)[0],pair);}return[...map.values()].join('; ');}function output(v){process.stdout.write(`${JSON.stringify(v,null,2)}\n`);}function fail(v){throw new Error(`JWB_PRODUCT:${v}`);}
