#!/usr/bin/env node
import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
import { chmodSync, existsSync, writeFileSync, unlinkSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import * as k8s from '@kubernetes/client-node';
import { KubernetesGenerationDriver } from '../services/rdf-sync/src/kubernetes-generation-driver.js';
import { SparqlHttpBackend } from '../services/rdf-backends/src/sparql-http-backend.js';
import { RDF_BACKEND_PROFILES } from '../services/rdf-backends/src/profiles.js';

const CLUSTER='wfp-jwb-m10',CONTEXT=`k3d-${CLUSTER}`,KUBECONFIG='/tmp/wfp-jwb-m10-kubeconfig.yaml',NAMESPACE='jwb-query-local',action=process.argv[2],backend=process.argv.find(value=>value.startsWith('--backend='))?.slice(10)??'virtuoso',k3d=existsSync('/tmp/wfp-tools/k3d')?'/tmp/wfp-tools/k3d':'k3d';
if(!['create','runtime','qualify','destroy'].includes(action)||!['virtuoso','oxigraph','fuseki-tdb2'].includes(backend))fail('usage: jwb-m10 create|runtime|qualify|destroy [--backend=virtuoso|oxigraph|fuseki-tdb2]');
if(action==='destroy')destroy();else if(action==='create')create();else if(action==='runtime')await runtime();else await qualify();

function create(){assertDocker();const clusters=list();if(!clusters.some(({name})=>name===CLUSTER))run(k3d,['cluster','create',CLUSTER,'--servers','1','--agents','0','--wait','--timeout','300s','--kubeconfig-update-default=false']);writeFileSync(KUBECONFIG,capture(k3d,['kubeconfig','get',CLUSTER]),{mode:0o600});chmodSync(KUBECONFIG,0o600);assertCluster();run('kubectl',[...base(),'apply','-f','infrastructure/japan-wikibase/kubernetes/m10-system.yaml']);ensureSecret().then(()=>console.log('jwb m10 create: fixed local cluster and least-privilege namespaces ready')).catch(error=>fail(error.message));}
async function qualify(){assertCluster();const config=kube(),core=config.makeApiClient(k8s.CoreV1Api),apps=config.makeApiClient(k8s.AppsV1Api),password=await secretPassword(core),driver=new KubernetesGenerationDriver({backendType:backend,core,apps,storageSize:'512Mi'}),evidence={backend,runtime:'kubernetes',generationIsolation:null,restart:null,storageFailure:null,idempotency:null,cleanup:null};try{await driver.createGeneration({generationId:'gen-a'});await driver.createGeneration({generationId:'gen-b'});await waitHealthy(driver,'gen-a');await waitHealthy(driver,'gen-b');const a=driver.descriptor('gen-a'),b=driver.descriptor('gen-b');assert.notEqual(a.serviceName,b.serviceName);assert.notEqual(a.storageIdentity,b.storageIdentity);evidence.generationIsolation={a:{service:a.serviceName,storage:a.storageIdentity},b:{service:b.serviceName,storage:b.storageIdentity}};const pvcBefore=await pvcUid(core,a);await withBackend(core,driver,'gen-a',password,async rdf=>{await rdf.initialize({instanceId:`m10-${backend}-a`});await put(rdf,1);assert.equal(await ask(rdf),true);});await driver.restartGeneration({generationId:'gen-a'});await waitHealthy(driver,'gen-a');assert.equal(await pvcUid(core,a),pvcBefore);await withBackend(core,driver,'gen-a',password,async rdf=>assert.equal(await ask(rdf),true));evidence.restart={sameGeneration:'gen-a',samePvc:true,dataSurvived:true};await driver.stopGeneration({generationId:'gen-b'});await driver.stopGeneration({generationId:'gen-b'});assert.equal((await driver.getGenerationHealth({generationId:'gen-b'})).status,'unavailable');await driver.startGeneration({generationId:'gen-b'});await waitHealthy(driver,'gen-b');evidence.storageFailure={candidateStopped:'classified_unavailable',pvcRetained:true,recovered:true};await driver.retireGeneration({generationId:'gen-b'});await driver.retireGeneration({generationId:'gen-b'});await driver.startGeneration({generationId:'gen-b'});await waitHealthy(driver,'gen-b');evidence.idempotency={create:true,stop:true,retire:true,start:true};const managed=await driver.listManagedGenerations();assert.equal(managed.length,2);evidence.status='KUBERNETES_PHYSICAL_GENERATION_QUALIFIED';}finally{for(const id of['gen-b','gen-a']){await driver.deleteGeneration({generationId:id}).catch(()=>{});await driver.deleteGeneration({generationId:id}).catch(()=>{});}for(let i=0;i<120&&(await driver.listManagedGenerations()).length;i++)await sleep(250);evidence.cleanup={generationsRemaining:(await driver.listManagedGenerations()).length};}console.log(JSON.stringify(evidence,null,2));}
async function runtime(){assertCluster();await ensurePostgresSecret();run('docker',['build','--tag','wfp/jwb-runtime:m10','--file','infrastructure/japan-wikibase/kubernetes/Dockerfile.runtime','.']);run(k3d,['image','import','wfp/jwb-runtime:m10','--cluster',CLUSTER]);run('kubectl',[...base(),'apply','-f','infrastructure/japan-wikibase/kubernetes/m10-system.yaml']);run('kubectl',[...base(),'apply','-f','infrastructure/japan-wikibase/kubernetes/m10-runtime.yaml']);run('kubectl',[...base(),'-n','jwb-system','rollout','restart','deployment/query-router','deployment/generation-coordinator']);run('kubectl',[...base(),'-n','jwb-system','rollout','status','statefulset/controller-postgres','--timeout=300s']);run('kubectl',[...base(),'-n','jwb-system','wait','--for=condition=complete','job/controller-postgres-migrate','--timeout=300s']);run('kubectl',[...base(),'-n','jwb-system','rollout','status','deployment/generation-coordinator','--timeout=300s']);console.log('jwb m10 runtime: PostgreSQL and two Coordinators ready; Routers intentionally await an initial serving pointer');}
function destroy(){const clusters=list();if(!clusters.some(({name})=>name===CLUSTER)){console.log('jwb m10 destroy: cluster absent');return;}assertCluster();run(k3d,['cluster','delete',CLUSTER]);if(existsSync(KUBECONFIG))unlinkSync(KUBECONFIG);console.log('jwb m10 destroy: fixed disposable cluster removed');}
async function ensureSecret(){const core=kube().makeApiClient(k8s.CoreV1Api),body={metadata:{name:'jwb-virtuoso-admin',namespace:NAMESPACE,labels:{'wikibase-federation.lodac.nii.ac.jp/environment':'local'}},type:'Opaque',data:{password:Buffer.from(randomBytes(24).toString('base64url')).toString('base64')}};try{await core.createNamespacedSecret({namespace:NAMESPACE,body});}catch(error){if(status(error)!==409)throw error;}}
async function ensurePostgresSecret(){const core=kube().makeApiClient(k8s.CoreV1Api),password=randomBytes(24).toString('base64url'),url=`postgresql://jwb:${password}@controller-postgres.jwb-system.svc.cluster.local:5432/jwb`,body={metadata:{name:'controller-postgres',namespace:'jwb-system',labels:{'wikibase-federation.lodac.nii.ac.jp/environment':'local'}},type:'Opaque',data:{password:Buffer.from(password).toString('base64'),url:Buffer.from(url).toString('base64')}};try{await core.createNamespacedSecret({namespace:'jwb-system',body});}catch(error){if(status(error)!==409)throw error;}}
async function secretPassword(core){const value=unwrap(await core.readNamespacedSecret({namespace:NAMESPACE,name:'jwb-virtuoso-admin'}));return Buffer.from(value.data.password,'base64').toString();}
async function waitHealthy(driver,id){for(let i=0;i<300;i++){const h=await driver.getGenerationHealth({generationId:id});if(h.status==='healthy')return;await sleep(500);}throw new Error(`generation health timeout ${id}`);}
async function withBackend(core,driver,id,password,operation){const d=driver.descriptor(id),pod=await waitReadyPod(core,id),local={virtuoso:28890,oxigraph:27878,'fuseki-tdb2':23030}[backend]+(id==='gen-b'?1:0),child=spawn('kubectl',[...base(),'-n',NAMESPACE,'port-forward',`pod/${pod.metadata.name}`,`${local}:${{virtuoso:8890,oxigraph:7878,'fuseki-tdb2':3030}[backend]}`],{stdio:'ignore'});try{await waitPort(local);const baseUrl=`http://127.0.0.1:${local}`,urls=backend==='virtuoso'?{queryUrl:`${baseUrl}/sparql`,updateUrl:`${baseUrl}/sparql-auth`,graphStoreUrl:`${baseUrl}/sparql-graph-crud-auth`,digestAuth:{username:'dba',password}}:backend==='oxigraph'?{queryUrl:`${baseUrl}/query`,updateUrl:`${baseUrl}/update`,graphStoreUrl:`${baseUrl}/store`}:{queryUrl:`${baseUrl}/jwb/query`,updateUrl:`${baseUrl}/jwb/update`,graphStoreUrl:`${baseUrl}/jwb/data`};await operation(new SparqlHttpBackend({...urls,metadata:RDF_BACKEND_PROFILES[backend]}));}finally{child.kill('SIGTERM');}}
async function waitReadyPod(core,id){for(let i=0;i<200;i++){const pods=unwrap(await core.listNamespacedPod({namespace:NAMESPACE,labelSelector:`wikibase-federation.lodac.nii.ac.jp/generation-id=${id},wikibase-federation.lodac.nii.ac.jp/backend-type=${backend}`})).items??[],ready=pods.filter(pod=>!pod.metadata?.deletionTimestamp&&pod.status?.conditions?.some(c=>c.type==='Ready'&&c.status==='True')).sort((a,b)=>String(b.metadata?.creationTimestamp).localeCompare(String(a.metadata?.creationTimestamp)))[0];if(ready)return ready;await sleep(250);}throw new Error(`ready Pod timeout ${id}`);}
async function put(rdf,version){const path=`/tmp/wfp-jwb-m10-${backend}.nt`;writeFileSync(path,`<urn:jwb:item:Q1> <http://schema.org/version> "${version}" .\n`,{mode:0o600});try{await rdf.replaceNamedGraph({graphIri:'urn:jwb:entity:Q1',source:path,mediaType:'application/n-triples'});}finally{unlinkSync(path);}}
async function ask(rdf){const response=await fetch(rdf.queryUrl,{method:'POST',headers:{accept:'application/sparql-results+json','content-type':'application/sparql-query'},body:'ASK { GRAPH <urn:jwb:entity:Q1> { ?s ?p ?o } }'});return response.ok&&(await response.json()).boolean===true;}
async function pvcUid(core,d){return unwrap(await core.readNamespacedPersistentVolumeClaim({namespace:NAMESPACE,name:`${d.workloadName}-data`})).metadata.uid;}
async function waitPort(port){for(let i=0;i<100;i++){try{const response=await fetch(`http://127.0.0.1:${port}`,{redirect:'manual'});if(response.status)return;}catch{}await sleep(100);}throw new Error('port-forward timeout');}
function assertDocker(){const [os,arch]=capture('docker',['info','--format','{{.OperatingSystem}}\n{{.Architecture}}']).trim().split('\n');if(!/Docker Desktop/u.test(os)||arch!=='aarch64')fail(`requires ARM64 Docker Desktop: ${os} ${arch}`);}
function assertCluster(){if(!existsSync(KUBECONFIG))fail('dedicated M10 kubeconfig missing');const current=capture('kubectl',[...base(),'config','current-context']).trim(),server=capture('kubectl',[...base(),'config','view','--minify','-o','jsonpath={.clusters[0].cluster.server}']).trim();if(current!==CONTEXT||!/^https:\/\/(?:127\.0\.0\.1|localhost|0\.0\.0\.0):[0-9]+$/u.test(server)||/utirik|prod|production/iu.test(server))fail(`refusing Kubernetes target ${current} ${server}`);}
function kube(){assertCluster();const value=new k8s.KubeConfig();value.loadFromFile(KUBECONFIG);value.setCurrentContext(CONTEXT);return value;}function base(){return['--kubeconfig',KUBECONFIG,'--context',CONTEXT];}function list(){return JSON.parse(capture(k3d,['cluster','list','-o','json'])||'[]');}function capture(command,args){return execFileSync(command,args,{encoding:'utf8',stdio:['ignore','pipe','pipe']});}function run(command,args){execFileSync(command,args,{stdio:'inherit'});}function unwrap(value){return value?.body??value;}function status(error){return error?.statusCode??error?.response?.statusCode??error?.code;}function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}function fail(message){throw new Error(`M10 safety guard: ${message}`);}
