#!/usr/bin/env node
import pg from'pg';
import{loadConfig}from'./config.js';
import{CoordinatorMetrics}from'./metrics.js';
import{CoordinatorLogger}from'./logger.js';
import{createCoordinatorHealthServer}from'./health-server.js';
import{PostgresGenerationCoordinatorRepository}from'../../../services/rdf-sync/src/postgres-generation-coordinator-repository.js';
import{GenerationCoordinatorRuntime}from'../../../services/rdf-sync/src/generation-coordinator-runtime.js';
import{LocalComposeGenerationDriver}from'../../../services/rdf-sync/src/local-compose-generation-driver.js';
import{createInClusterKubernetesGenerationDriver}from'../../../services/rdf-sync/src/kubernetes-generation-driver.js';
import{verifyCoordinatorSchema}from'../../../services/rdf-sync/src/coordinator-schema-readiness.js';
const config=loadConfig(),pool=new pg.Pool({connectionString:config.databaseUrl,max:4,connectionTimeoutMillis:5000});pool.on('error',()=>{});const repository=new PostgresGenerationCoordinatorRepository({pool,leaseMs:config.leaseMs}),metrics=new CoordinatorMetrics(),logger=new CoordinatorLogger(),drivers=new Map(['virtuoso','oxigraph','fuseki-tdb2'].map(type=>[type,config.runtimeType==='kubernetes'?createInClusterKubernetesGenerationDriver({backendType:type}):new LocalComposeGenerationDriver({backendType:type,adminPassword:type==='virtuoso'?config.virtuosoPassword:undefined})])),routerBase=config.runtimeType==='kubernetes'?'http://query-router.jwb-system.svc.cluster.local:8080':'http://127.0.0.1',routerObserver={observes:async(generationId,version)=>{const targets=config.runtimeType==='kubernetes'?[`${routerBase}/sparql`,`${routerBase}/sparql`]:[`${routerBase}:19200/sparql`,`${routerBase}:19201/sparql`];for(const url of targets){try{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/sparql-query'},body:'ASK { ?s ?p ?o }'});if(!response.ok||response.headers.get('x-jwb-pointer-version')!==String(version))return false;}catch{return false;}}return /^gen-[a-z0-9][a-z0-9-]{0,58}$/u.test(generationId);}},runtime=new GenerationCoordinatorRuntime({repository,drivers,routerObserver,metrics,logger,pollIntervalMs:config.pollIntervalMs,crash:point=>{if(config.crashAt===point)process.exit(86);}}),health=createCoordinatorHealthServer({runtime,metrics,port:config.port,host:config.runtimeType==='kubernetes'?'0.0.0.0':'127.0.0.1'});await health.start();while(!runtime.stopping&&!await verifyCoordinatorSchema(pool))await new Promise(resolve=>setTimeout(resolve,1000));runtime.setSchemaReady(true);const running=runtime.run();for(const signal of['SIGINT','SIGTERM'])process.once(signal,()=>runtime.stop());await running;await health.close();await pool.end();
