import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { GenerationCoordinatorRuntime } from './generation-coordinator-runtime.js';

const metrics={increment(){},set(){}},logger={log(){}};
function fixture(state,evidence={}){const transitions=[],crashes=[],repository={pool:{query:async()=>{}},ensureGeneration:async()=>{},transition:async v=>{transitions.push(v);return v;},setGenerationState:async()=>{},generationEvidence:async()=>evidence,pointer:async()=>({generationId:'gen-a',previousGenerationId:null,version:1}),operationPromotion:async()=>null,preparePromotion:async()=>({id:'00000000-0000-4000-8000-000000000001',phase:'PREPARING'}),beginRetirement:async()=>{}},driver={createGeneration:async()=>{}},runtime=new GenerationCoordinatorRuntime({repository,drivers:new Map([['virtuoso',driver]]),routerObserver:{observes:async()=>true},metrics,logger,crash:p=>crashes.push(p)}),op={id:'00000000-0000-4000-8000-000000000002',sourceIdentity:'m9d',queryServiceId:'m9d-query',candidateGenerationId:'gen-b',backendType:'virtuoso',state,fence:1,snapshotCursor:{timestamp:'2026-01-01T00:00:00Z',rcid:1},targetCursor:{timestamp:'2026-01-01T00:00:01Z',rcid:2}};return{runtime,op,transitions,crashes};}
test('candidate creation uses driver and exposes physical crash E before load state',async()=>{const f=fixture('CREATING_GENERATION');await f.runtime.reconcile(f.op);assert.deepEqual(f.crashes,['E_AFTER_CANDIDATE_CREATED']);assert.equal(f.transitions[0].to,'LOADING_SNAPSHOT');});
test('catch-up gate refuses incomplete evidence and validation requires full contract',async()=>{let f=fixture('WAITING_FOR_CATCHUP',{catchup_cursor_timestamp:'2026-01-01T00:00:00Z',catchup_cursor_rcid:1,schema_state:'CURRENT',failed_entities:0});await f.runtime.reconcile(f.op);assert.equal(f.transitions[0].to,'WAITING_FOR_CATCHUP');f=fixture('VALIDATING',{state:'READY',validation_status:'VALID',normalization_model:'jwb-rdf-normalization-v1',partition_model:'jwb-partition-v1',generation_manifest:{}});await f.runtime.reconcile(f.op);assert.deepEqual(f.crashes,['H_READY_BEFORE_PROMOTION']);});

function cleanupFixture(crashPoint){let journalState='RETIRED';const events=[],deletionToken=randomUUID(),repository={pool:{query:async()=>{}},operationRetirement:async()=>({generationId:'gen-old',state:journalState}),authorizePhysicalDeletion:async()=>{journalState='PHYSICAL_DELETE_PENDING';return{generationId:'gen-old',state:journalState,deletionToken};},recordDeletionPlan:async()=>events.push('plan-persisted'),markDeletionFence:async()=>events.push('fence-persisted'),assertDeletionAuthority:async()=>events.push('authorized'),recordDeletionIntent:async()=>{},recordDeletionAccepted:async()=>{},recordAbsenceConfirmed:async()=>{},recordDeletionFailure:async()=>{},confirmPhysicalDeletion:async()=>{journalState='PHYSICALLY_DELETED';return{generationId:'gen-old',state:journalState};},finalizeRetirement:async()=>{journalState='METADATA_FINALIZED';return{generationId:'gen-old',state:journalState};},transition:async()=>({})},driver={planDeleteGeneration:async()=>{events.push('planned');return{};},markDeletionAuthority:async plan=>{events.push('marked');return plan;},executeDeletePlan:async(_plan,{authorize})=>{events.push('execute');await authorize('first');}},op={id:'00000000-0000-4000-8000-000000000002',candidateGenerationId:'gen-old',backendType:'virtuoso',state:'CLEANING_UP',fence:7},runtime=new GenerationCoordinatorRuntime({repository,drivers:new Map([['virtuoso',driver]]),routerObserver:{},metrics,logger,crash:point=>{if(point===crashPoint){events.push('crash');throw new Error('CRASH');}}});return{runtime,op,events,getState:()=>journalState};}
test('hard crash point follows durable plan and fence but precedes execute',async()=>{const f=cleanupFixture('AFTER_DELETE_PREFLIGHT_BEFORE_FIRST_DELETE');await assert.rejects(f.runtime.reconcile(f.op),/CRASH/u);assert.deepEqual(f.events,['planned','marked','plan-persisted','fence-persisted','crash']);assert.equal(f.getState(),'PHYSICAL_DELETE_PENDING');});
test('cleanup after execution finalizes metadata',async()=>{const f=cleanupFixture(null);await f.runtime.reconcile(f.op);assert.equal(f.getState(),'METADATA_FINALIZED');assert.ok(f.events.includes('execute'));});
test('operation loop refuses to start before migration readiness',async()=>{const f=fixture('REBUILD_REQUESTED');await assert.rejects(f.runtime.run(),/SCHEMA_MIGRATION_REQUIRED/u);assert.equal(await f.runtime.ready(),false);});
