import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import { KubernetesGenerationDriver, kubernetesGenerationBackend } from './kubernetes-generation-driver.js';

function fixture() {
  const state={sets:new Map(),services:new Map(),claims:new Map(),deletions:[]},wrap=(body)=>({body}),missing=()=>Object.assign(new Error('missing'),{statusCode:404}),conflict=()=>Object.assign(new Error('exists'),{statusCode:409});let sequence=0;
  const create=(map)=>(async({body})=>{if(map.has(body.metadata.name))throw conflict();const value=structuredClone(body);value.metadata.uid=`uid-${++sequence}`;value.metadata.resourceVersion='1';map.set(body.metadata.name,value);return wrap(value);}),read=(map)=>(async({name})=>{if(!map.has(name))throw missing();return wrap(map.get(name));}),remove=(map,kind)=>(async({name,body})=>{if(!map.has(name))throw missing();const value=map.get(name),preconditions=body?.preconditions;assert.equal(preconditions?.uid,value.metadata.uid);assert.equal(preconditions?.resourceVersion,value.metadata.resourceVersion);state.deletions.push(kind);map.delete(name);}),patch=async({name,body})=>{const value=state.sets.get(name);if(!value)throw missing();for(const op of body){if(op.path==='/spec/replicas')value.spec.replicas=op.value;if(op.path==='/spec/template/metadata/annotations')value.spec.template.metadata.annotations=op.value;}return wrap(value);};
  const patchService=async({name,body})=>{const value=state.services.get(name);if(!value)throw missing();if(body.metadata.resourceVersion!==value.metadata.resourceVersion)throw Object.assign(new Error('conflict'),{statusCode:409});value.metadata.annotations=body.metadata.annotations;value.metadata.resourceVersion=String(Number(value.metadata.resourceVersion)+1);return wrap(value);};
  const core={createNamespacedPersistentVolumeClaim:create(state.claims),readNamespacedPersistentVolumeClaim:read(state.claims),deleteNamespacedPersistentVolumeClaim:remove(state.claims,'pvc'),createNamespacedService:create(state.services),readNamespacedService:read(state.services),patchNamespacedService:patchService,deleteNamespacedService:remove(state.services,'service')};
  const apps={createNamespacedStatefulSet:create(state.sets),readNamespacedStatefulSet:read(state.sets),deleteNamespacedStatefulSet:remove(state.sets,'workload'),patchNamespacedStatefulSet:patch,listNamespacedStatefulSet:async()=>wrap({items:[...state.sets.values()]})};return{state,core,apps};
}

test('derives fixed Kubernetes identity and creates isolated owned workload/service/PVC idempotently',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'virtuoso',core:f.core,apps:f.apps});const a=await driver.createGeneration({generationId:'gen-a'}),b=await driver.createGeneration({generationId:'gen-b'});await driver.createGeneration({generationId:'gen-a'});assert.equal(a.runtimeType,'kubernetes');assert.notEqual(a.serviceName,b.serviceName);assert.equal(f.state.claims.size,2);assert.equal(f.state.sets.get(a.workloadName).spec.template.spec.containers[0].env[0].valueFrom.secretKeyRef.name,'jwb-virtuoso-admin');});
test('rejects ownership mismatch before mutation and fixed target prevents arbitrary namespace/backend',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps});const d=await driver.createGeneration({generationId:'gen-a'});f.state.sets.get(d.workloadName).metadata.labels['wikibase-federation.lodac.nii.ac.jp/instance-id']='foreign';await assert.rejects(driver.stopGeneration({generationId:'gen-a'}),/OWNERSHIP_MISMATCH/u);assert.throws(()=>new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps,namespace:'prod'}),/configuration/u);assert.throws(()=>driver.descriptor('bad;delete'),/generation/u);});
test('stop retire delete and journal-proven absent delete are structured and idempotent',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'fuseki-tdb2',core:f.core,apps:f.apps}),evidence={};await driver.createGeneration({generationId:'gen-c'});await driver.stopGeneration({generationId:'gen-c'});await driver.retireGeneration({generationId:'gen-c'});await driver.deleteGeneration({generationId:'gen-c',onIntent:async value=>{evidence[value.kind]={status:'DELETE_INTENT',uid:value.uid,resourceVersion:value.resourceVersion};},onProgress:async value=>{evidence[value.kind].status='DELETED';}});await driver.deleteGeneration({generationId:'gen-c',deletionEvidence:evidence});assert.deepEqual(await driver.listManagedGenerations(),[]);assert.equal(await driver.generationExists({generationId:'gen-c'}),false);});
test('delete preflights every resource before mutating any resource',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),d=await driver.createGeneration({generationId:'gen-safe'});f.state.services.get(d.serviceName).metadata.labels['wikibase-federation.lodac.nii.ac.jp/instance-id']='foreign';await assert.rejects(driver.deleteGeneration({generationId:'gen-safe'}),/OWNERSHIP_MISMATCH:service/u);assert.equal(f.state.deletions.length,0);assert.equal(f.state.sets.size,1);assert.equal(f.state.services.size,1);assert.equal(f.state.claims.size,1);});
test('delete rejects a changed preflight snapshot before the first mutation',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),d=await driver.createGeneration({generationId:'gen-race'}),plan=await driver.planDeleteGeneration({generationId:'gen-race'});f.state.claims.get(`${d.workloadName}-data`).metadata.resourceVersion='2';await assert.rejects(driver.executeDeletePlan(plan),/RESOURCE_VERSION_MISMATCH:pvc/u);assert.equal(f.state.deletions.length,0);});
test('every ownership mismatch permutation produces zero mutation',async()=>{for(const [kind,mapName,name]of[['workload','sets','workloadName'],['service','services','serviceName'],['pvc','claims','pvcName']]){const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),d=await driver.createGeneration({generationId:`gen-wrong-${kind}`}),resourceName=name==='pvcName'?`${d.workloadName}-data`:d[name];f.state[mapName].get(resourceName).metadata.labels['wikibase-federation.lodac.nii.ac.jp/generation-id']='gen-foreign';await assert.rejects(driver.deleteGeneration({generationId:`gen-wrong-${kind}`}),/OWNERSHIP_MISMATCH/u);assert.deepEqual(f.state.deletions,[]);assert.equal(f.state.sets.size,1);assert.equal(f.state.services.size,1);assert.equal(f.state.claims.size,1);}});
test('partial API failure is explicit and journal-proven retry does not recreate',async()=>{const f=fixture(),original=f.core.deleteNamespacedService,calls=[],evidence={},driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),onIntent=async value=>{evidence[value.kind]={status:'DELETE_INTENT',uid:value.uid,resourceVersion:value.resourceVersion};},onProgress=async value=>{calls.push(value);evidence[value.kind].status='DELETED';};await driver.createGeneration({generationId:'gen-partial'});let failed=false;f.core.deleteNamespacedService=async input=>{if(!failed){failed=true;throw new Error('KUBERNETES_API_OUTAGE');}return original(input);};await assert.rejects(driver.deleteGeneration({generationId:'gen-partial',onIntent,onProgress}),/API_OUTAGE/u);assert.equal(calls[0].result,'ABSENT_CONFIRMED');await driver.deleteGeneration({generationId:'gen-partial',deletionEvidence:evidence,onIntent,onProgress});assert.deepEqual(calls.slice(1).map(value=>value.result),['ABSENT_CONFIRMED','RESOURCE_ALREADY_DELETED_BY_OPERATION','RESOURCE_ALREADY_DELETED_BY_OPERATION','ABSENT_CONFIRMED']);});

test('service authority marker fences stale plans and PVC gets final authorization',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),operationId=randomUUID(),deletionToken=randomUUID();await driver.createGeneration({generationId:'gen-fenced'});let plan=await driver.planDeleteGeneration({generationId:'gen-fenced',operationId,operationFence:1,deletionToken});plan=await driver.markDeletionAuthority(plan);const gates=[];await driver.executeDeletePlan(plan,{authorize:async kind=>{gates.push(kind);}});assert.deepEqual(gates,['first','pvc']);assert.deepEqual(f.state.deletions,['workload','pvc','service']);});
test('newer authority marker rejects a stale fenced plan before delete',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),operationId=randomUUID();await driver.createGeneration({generationId:'gen-takeover'});let stale=await driver.planDeleteGeneration({generationId:'gen-takeover',operationId,operationFence:1,deletionToken:randomUUID()});stale=await driver.markDeletionAuthority(stale);let current=await driver.planDeleteGeneration({generationId:'gen-takeover',operationId,operationFence:2,deletionToken:randomUUID()});current=await driver.markDeletionAuthority(current);await assert.rejects(driver.executeDeletePlan(stale,{authorize:async()=>{}}),/STALE_COORDINATOR_FENCE/u);assert.deepEqual(f.state.deletions,[]);assert.equal(current.operationFence,2);});
test('missing before cleanup is rejected with zero mutation',async()=>{const f=fixture(),driver=new KubernetesGenerationDriver({backendType:'oxigraph',core:f.core,apps:f.apps}),d=await driver.createGeneration({generationId:'gen-missing'});f.state.services.delete(d.serviceName);await assert.rejects(driver.deleteGeneration({generationId:'gen-missing'}),/RESOURCE_MISSING_UNEXPECTED:service/u);assert.deepEqual(f.state.deletions,[]);assert.equal(f.state.sets.size,1);assert.equal(f.state.claims.size,1);});
test('worker data-plane backend accepts only a driver-derived descriptor and needs no Kubernetes client',()=>{const driver=new KubernetesGenerationDriver({backendType:'virtuoso',core:{},apps:{}}),descriptor=driver.descriptor('gen-a'),backend=kubernetesGenerationBackend({descriptor,adminPassword:'0123456789abcdef'});assert.equal(backend.queryUrl,descriptor.queryEndpoint);assert.throws(()=>kubernetesGenerationBackend({descriptor:{...descriptor,internalUpdateEndpoint:'http://foreign/update'},adminPassword:'0123456789abcdef'}),/untrusted/u);});
