import assert from'node:assert/strict';import test from'node:test';import pg from'pg';import{migrateJwb,JWB_MIGRATIONS}from'../../../packages/jwb-database/src/jwb-migrations.js';import{bootstrapStandaloneJwb}from'./standalone-bootstrap.js';
const integration=process.env.TEST_JWB_DATABASE_URL?test:test.skip;
integration('JWB-only migrations and standalone bootstrap are isolated and idempotent',async context=>{
  const pool=new pg.Pool({connectionString:process.env.TEST_JWB_DATABASE_URL});context.after(()=>pool.end());await migrateJwb(pool);await bootstrapStandaloneJwb({pool,backendType:'oxigraph'});await bootstrapStandaloneJwb({pool,backendType:'oxigraph'});
  const migrations=await pool.query('SELECT version FROM schema_migrations ORDER BY version'),controller=await pool.query("SELECT count(*)::int count FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'controller_%'"),pointer=await pool.query("SELECT generation_id,version FROM rdf_serving_pointer WHERE query_service_id='jwb-standalone-query'"),generations=await pool.query("SELECT generation_id,state,protection_state FROM rdf_generation WHERE source_identity='jwb-standalone' ORDER BY generation_id");
  assert.deepEqual(migrations.rows.map(v=>v.version),JWB_MIGRATIONS);assert.equal(controller.rows[0].count,0);assert.deepEqual(pointer.rows[0],{generation_id:'gen-a',version:'1'});assert.deepEqual(generations.rows.map(v=>[v.generation_id,v.state,v.protection_state]),[['gen-a','SERVING','SERVING'],['gen-b','READY','NONE']]);
  await pool.query("UPDATE rdf_generation SET state='RETIRING',protection_state='ROLLBACK' WHERE source_identity='jwb-standalone' AND generation_id='gen-a'");await pool.query("UPDATE rdf_generation SET state='SERVING',protection_state='SERVING',promoted_at=now() WHERE source_identity='jwb-standalone' AND generation_id='gen-b'");
  await bootstrapStandaloneJwb({pool,backendType:'oxigraph'});
  const preserved=await pool.query("SELECT generation_id,state,protection_state FROM rdf_generation WHERE source_identity='jwb-standalone' ORDER BY generation_id");assert.deepEqual(preserved.rows.map(v=>[v.generation_id,v.state,v.protection_state]),[['gen-a','RETIRING','ROLLBACK'],['gen-b','SERVING','SERVING']]);
});
